[build]
    functions="functions"

[[redirects]]
    to="/.netlify/functions/api:splat"
    from="/*"
    status=200 
    force = true
    /api/*  https://doodle-ooo-api.cyclic.app/*  200
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
