[build]
    functions="functions"

[[redirects]]
    to="/.netlify/functions/api:splat"
    from="/*"
    status=200 
    force = true
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"


    [[redirects]]
  from = "/pathx"
  to = "https://example.com/patha"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"